development:
  adapter: postgresql
  database: db_harry_potter
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: db_harry_potter
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db_harry_potter
  pool: 5
  timeout: 5000
